CREATE TABLE account (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    profile_photo_url VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE task (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(30),
    due_date DATE,
    account_id INT,
    CONSTRAINT fk_task_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT chk_task_status CHECK (status IN ('BACKLOG','TO_DO', 'IN_PROGRESS', 'TESTING', 'DONE')),
    CONSTRAINT chk_task_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE token (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(512) NOT NULL UNIQUE,
    token_type VARCHAR(20) NOT NULL,
    expired BOOLEAN NOT NULL DEFAULT FALSE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    account_id INT NOT NULL,
    CONSTRAINT fk_token_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT chk_token_type CHECK (token_type IN ('BEARER'))
);
