openapi: 3.0.1
info:
  title: collab-task
  description: Collaborative Task Management System
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Server

paths:
  /account:
    $ref: './path/account.yaml'
  /account/{id}:
    $ref: './path/account-id.yaml'

  /task:
    $ref: './path/task.yaml'
  /task/{id}:
    $ref: './path/task-id.yaml'
