spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.collabtaskapi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/collabtaskapi.log